server:
  port: 8081
  servlet:
    context-path: /api

spring:
  datasource:
    url: jdbc:postgresql://antonio-dev.go.ro:15884/clinicDb
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.yaml
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

jwt:
  secret: ${JWT_SECRET:cnLbAkFva0RYi+kvpPkLCBrSCSz91CnUkYAXAvU60RoPGjTMHRiYuCaLRMVfRQ+8}

clinic:
  documents:
    upload-dir: uploads/documents

cors:
  allowed-origins: ${FRONTEND_URL:http://localhost:5173}